version: "3"
services:
  app:
    build: 
      context: .
    working_dir: /app
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: "yarn start"